### ISSUE TITLE
Panic in render_backend when saving a wrench recording to yaml

### ISSUE THREAD

**Issue by rlhunt** [servo/webrender#1060]
```
[rhunt@rhunt-thinkpad wrench]$ RUST_BACKTRACE=1 cargo run -- --save yaml replay ../../firefox/wr-record-1.bin 
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/home/rhunt/src/webrender/target/debug/wrench --save yaml replay ../../firefox/wr-record-1.bin`
OpenGL version 4.5 (Core Profile) Mesa 17.0.2, Mesa DRI Intel(R) HD Graphics P530 (Skylake GT2) 
hidpi factor: 1 (native 1)
Shader override path: None
Warning: binary file ApiMsg type mismatch: expected 0x3c2747c08416cc16, found 0xbd69ed4130599056
Frame 0 offset: 16
Frame 1 offset: 41
thread 'RenderBackend' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:323
stack backtrace:
   1:     0x55aff9cffd1c - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55aff9d037ae - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x55aff9d033b4 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x55aff9d03c4b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x55aff9d03ae4 - std::panicking::begin_panic::hd6eb68e27bdf6140
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x55aff9d03a09 - std::panicking::begin_panic_fmt::hfea5965948b877f8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x55aff9d03997 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x55aff9d3009d - core::panicking::panic_fmt::hc0f6d7b2c300cdd9
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x55aff9d2ffd4 - core::panicking::panic::h7abeb5b818ec354e
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:49
  10:     0x55aff8e45a6a - <core::option::Option<T>>::unwrap::h778777df073935c8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/macros.rs:21
  11:     0x55aff9174e39 - wrench::yaml_frame_writer::ClipIdMapper::map::hda0a02fa1e122d1e
                        at /home/rhunt/src/webrender/wrench/src/yaml_frame_writer.rs:863
  12:     0x55aff9170ab6 - wrench::yaml_frame_writer::YamlFrameWriter::write_display_list_items::he7bd51cfb8511768
                        at /home/rhunt/src/webrender/wrench/src/yaml_frame_writer.rs:499
  13:     0x55aff9174157 - wrench::yaml_frame_writer::YamlFrameWriter::write_display_list::h207fb03c1bd145d5
                        at /home/rhunt/src/webrender/wrench/src/yaml_frame_writer.rs:755
  14:     0x55aff916e235 - wrench::yaml_frame_writer::YamlFrameWriter::finish_write_root_display_list::h2786d59095380d38
                        at /home/rhunt/src/webrender/wrench/src/yaml_frame_writer.rs:325
  15:     0x55aff9174cc0 - <wrench::yaml_frame_writer::YamlFrameWriterReceiver as webrender::record::ApiRecordingReceiver>::write_payload::h38258bd34fc7c69a
                        at /home/rhunt/src/webrender/wrench/src/yaml_frame_writer.rs:836
  16:     0x55aff9770349 - webrender::render_backend::RenderBackend::run::h91b93b9e86c627a2
                        at /home/rhunt/src/webrender/webrender/src/render_backend.rs:206
  17:     0x55aff97aee3b - webrender::renderer::Renderer::new::{{closure}}::h9924d6acb4e637e8
                        at /home/rhunt/src/webrender/webrender/src/renderer.rs:877
  18:     0x55aff971d1ca - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::h37cbb148c57c51fe
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:296
  19:     0x55aff94de3a9 - std::panicking::try::do_call::hfc46f7b6e2cb8bb1
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:460
  20:     0x55aff9d0ab0a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  21:     0x55aff94dde33 - std::panicking::try::h8f53f1eb707bd9f0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
  22:     0x55aff94dbdb4 - std::panic::catch_unwind::h26d5d97f682ecf08
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
  23:     0x55aff94dd3cb - std::thread::Builder::spawn::{{closure}}::h9320c34667921586
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/thread/mod.rs:357
  24:     0x55aff95a9492 - <F as alloc::boxed::FnBox<A>>::call_box::hcd012d160000f098
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/liballoc/boxed.rs:614
  25:     0x55aff9d02af4 - std::sys::imp::thread::Thread::new::thread_start::he668872ac11287ba
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/liballoc/boxed.rs:624
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  26:     0x7fc62bbaa2e6 - start_thread
  27:     0x7fc62b6d454e - clone
  28:                0x0 - <unknown>
```

cc @mrobinson

**Comment by rlhunt** [comment]
```diff
-    fn map(&self, id: &ScrollLayerId) -> usize {
-        *self.hash_map.get(id).unwrap()
+    fn map_or_add_id(&mut self, id: &ScrollLayerId) -> usize {
+        if let Some(id) = self.hash_map.get(id) {
+            return *id
+        }
+
+        self.add_id(*id)
     }
```

I only briefly looked into the logic of ClipIdMapper, but it seems something like the diff above might be more applicable?

**Comment by mrobinson** [comment]
@rlhunt Is it posible to get a copy of the bin file you are trying to replay?

**Comment by rlhunt** [comment]
Yes, I've uploaded a copy of it to [gdrive](https://drive.google.com/file/d/0B84Jf1P5fuSpSng2SDR6VkVNMFk/view?usp=sharing). It's a recording of gecko of me opening the browser and closing out right away.

**Comment by mrobinson** [comment]
@rlhunt Hrm. The binary file doesn't produce the same error on my machine, but I do see this in my output as well:
```
Warning: binary file ApiMsg type mismatch: expected 0x43ab86b27c2a996b, found 0xbd69ed4130599056
```

The only way this error could occur is if the display list is malformed and it is using a ScrollLayerId before defining it in some way.

**Comment by rlhunt** [comment]
This hasn't happened to me any more, so it was probably a fluke.
