### ISSUE TITLE
Crash on macos when opening new tab: missing scroll_node_id

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1682]
Crashing on `let scroll_node = &self.clip_scroll_tree.nodes[&group.scroll_node_id];` in `recalculate_clip_scroll_groups`.

```
hread 'RenderBackend' panicked at 'no entry found for key', src/libcore/option.rs:823
stack backtrace:
   0:        0x114c40ca3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h884a721e113c3303
   1:        0x114c4d163 - std::panicking::default_hook::{{closure}}::h7a7d734b2824d103
   2:        0x114c4cdac - std::panicking::default_hook::h3eb11bd6cbfdc331
   3:        0x114c4f2d7 - std::panicking::rust_panic_with_hook::h8b9b25777425677b
   4:        0x114c4f174 - std::panicking::begin_panic::h69fe06a9d67b6165
   5:        0x114c4f0e2 - std::panicking::begin_panic_fmt::haf8695bfb6c52436
   6:        0x114c4f047 - rust_begin_unwind
   7:        0x114c62230 - core::panicking::panic_fmt::hfedd6515bcee8bb1
   8:        0x114c6229d - core::option::expect_failed::h28a2a19f2decdd9c
   9:        0x114a6f26d - <core::option::Option<T>>::expect::hac168a503560cf99
  10:        0x114a6aa40 - <std::collections::hash::map::HashMap<K, V, S> as core::ops::Index<&'a Q>>::index::h49667e24ac931475
  11:        0x114aac70b - webrender::frame_builder::LayerRectCalculationAndCullingPass::recalculate_clip_scroll_groups::ha12a9988683a7b11
  12:        0x114aac123 - webrender::frame_builder::LayerRectCalculationAndCullingPass::run::hd3e2520f54469c0c
  13:        0x114aac0d7 - webrender::frame_builder::LayerRectCalculationAndCullingPass::create_and_run::h60f36bf6dcf35778
  14:        0x114aabaf5 - webrender::frame_builder::FrameBuilder::build::hc5fbbbd64c8dd9a0
  15:        0x114aa5016 - webrender::frame::Frame::build_frame::{{closure}}::h56c88a7da31406a1
  16:        0x114a6e43d - <core::option::Option<T>>::map::h1fbda1ea03fdfd04
  17:        0x114aa4efd - webrender::frame::Frame::build_frame::h10c00026a03fa944
  18:        0x114aa4e0b - webrender::frame::Frame::build::hecb5934eb68e2522
  19:        0x114ab7da8 - webrender::render_backend::Document::render::h1d7175be681900e6
  20:        0x114ab89b3 - webrender::render_backend::RenderBackend::process_document::h8740921e449148ef
  21:        0x114ab8f50 - webrender::render_backend::RenderBackend::run::h9a2d1e5f24ff6a6d
  22:        0x114a3e3da - webrender::renderer::Renderer::new::{{closure}}::hb06ffa5ff03ac526
  23:        0x1149c69dd - std::sys_common::backtrace::__rust_begin_short_backtrace::h3f66ed1d6c9dd93d
  24:        0x114adb5bd - std::thread::Builder::spawn::{{closure}}::{{closure}}::h8e479e38eb51410d
  25:        0x114b0cd0d - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::hb2290a092864c045
  26:        0x114adbc8d - std::panicking::try::do_call::h2c53bc107a155b7c
Redirecting call to abort() to mozalloc_abort
```

https://github.com/servo/webrender/commit/0d6194ef44b56344132583987f59716f471a96a4 looks very suspicious.

**Comment by Gankro** [comment]
CC @mrobinson @glennw

**Comment by Gankro** [comment]
Notes: looks like this crash has been slumbering for a while; can't find where this broke. @jrmuizel bisected this innocuous gecko patch: https://hg.mozilla.org/mozilla-central/raw-rev/1fae43b4534c

Reverting this seems to fix it for me, but not jeff?

The missing clip seems to always be `Clip(3,1,PipelineId(1,1))`, and nothing else.

**Comment by Gankro** [comment]
Ok, solved! (ish)

So the crash is because of this:

```rust
        if composition_operations.will_make_invisible() {
            traversal.skip_current_stacking_context();
            return;
        }
```

Because that makes us skip this StackingContext:

```
  PushStackingContext(PushStackingContextDisplayItem { stacking_context: StackingContext { scroll_policy: Scrollable, transform: None, transform_style: Flat, perspective: None, mix_blend_mode: Normal } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(3, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(4, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Iframe(IframeDisplayItem { pipeline_id: PipelineId(1, 4) }), clip: ClipAndScrollInfo { scroll_node_id: Clip(4, 0, PipelineId(1, 1)), clip_node_id: None }
  PopStackingContext, clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
```

And the `Clip(3, 0)` (later translated into `Clip(3,1)`) is used by several items outside of it. 

<details>
  <summary>Full DisplayList</summary>

```
BuiltDisplayList: 
  PushNestedDisplayList, clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Rectangle(RectangleDisplayItem { color: ColorF { r: 0.9333334, g: 0.9333334, b: 0.9333334, a: 1 } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(1, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 25), stretch_size: 1259×32, tile_spacing: 1259×32, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(1, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(2, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Rectangle(RectangleDisplayItem { color: ColorF { r: 1, g: 1, b: 1, a: 1 } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(2, 0, PipelineId(1, 1)), clip_node_id: None }
  PushStackingContext(PushStackingContextDisplayItem { stacking_context: StackingContext { scroll_policy: Scrollable, transform: None, transform_style: Flat, perspective: None, mix_blend_mode: Normal } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(3, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(4, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Iframe(IframeDisplayItem { pipeline_id: PipelineId(1, 4) }), clip: ClipAndScrollInfo { scroll_node_id: Clip(4, 0, PipelineId(1, 1)), clip_node_id: None }
  PopStackingContext, clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 26), stretch_size: 54×16, tile_spacing: 54×16, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(1, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 3), stretch_size: 1259×72, tile_spacing: 1259×72, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(3, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 4), stretch_size: 1259×33, tile_spacing: 1259×33, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(3, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 27), stretch_size: 1259×33, tile_spacing: 1259×33, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(3, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(5, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Rectangle(RectangleDisplayItem { color: ColorF { r: 1, g: 1, b: 1, a: 0.3019608 } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(5, 0, PipelineId(1, 1)), clip_node_id: None }
  Border(BorderDisplayItem { widths: BorderWidths { left: 0, top: 0, right: 0, bottom: 1 }, details: Normal(NormalBorder { left: BorderSide { color: ColorF { r: 0, g: 0, b: 0, a: 1 }, style: None }, right: BorderSide { color: ColorF { r: 0, g: 0, b: 0, a: 1 }, style: None }, top: BorderSide { color: ColorF { r: 0, g: 0, b: 0, a: 1 }, style: None }, bottom: BorderSide { color: ColorF { r: 0.882353, g: 0.882353, b: 0.8862746, a: 1 }, style: Solid }, radius: BorderRadius { top_left: 0×0, top_right: 0×0, bottom_left: 0×0, bottom_right: 0×0 } }) }), clip: ClipAndScrollInfo { scroll_node_id: Clip(3, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(6, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  PushStackingContext(PushStackingContextDisplayItem { stacking_context: StackingContext { scroll_policy: Scrollable, transform: Some(Binding(PropertyBindingKey { id: PropertyBindingId { namespace: IdNamespace(98016), uid: 2 }, _phantom: PhantomData })), transform_style: Flat, perspective: None, mix_blend_mode: Normal } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(6, 0, PipelineId(1, 1)), clip_node_id: None }
  PushStackingContext(PushStackingContextDisplayItem { stacking_context: StackingContext { scroll_policy: Scrollable, transform: Some(Binding(PropertyBindingKey { id: PropertyBindingId { namespace: IdNamespace(98016), uid: 3 }, _phantom: PhantomData })), transform_style: Flat, perspective: None, mix_blend_mode: Normal } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(6, 0, PipelineId(1, 1)), clip_node_id: None }
  PopStackingContext, clip: ClipAndScrollInfo { scroll_node_id: Clip(6, 0, PipelineId(1, 1)), clip_node_id: None }
  PopStackingContext, clip: ClipAndScrollInfo { scroll_node_id: Clip(6, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(7, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(8, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 107), stretch_size: 20×20, tile_spacing: 20×20, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(8, 0, PipelineId(1, 1)), clip_node_id: None }
  PushStackingContext(PushStackingContextDisplayItem { stacking_context: StackingContext { scroll_policy: Scrollable, transform: None, transform_style: Flat, perspective: None, mix_blend_mode: Normal } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 108), stretch_size: 16×16, tile_spacing: 16×16, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(6, 0, PipelineId(1, 1)), clip_node_id: None }
  PopStackingContext, clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(9, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Text(TextDisplayItem { font_key: FontInstanceKey(IdNamespace(1), 22), color: ColorF { r: 0.97647065, g: 0.97647065, b: 0.9803922, a: 0.7 }, glyph_options: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(9, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 109), stretch_size: 28×28, tile_spacing: 28×28, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(6, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(10, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Rectangle(RectangleDisplayItem { color: ColorF { r: 0.97647065, g: 0.97647065, b: 0.9803922, a: 1 } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(10, 0, PipelineId(1, 1)), clip_node_id: None }
  Border(BorderDisplayItem { widths: BorderWidths { left: 0, top: 1, right: 0, bottom: 0 }, details: Normal(NormalBorder { left: BorderSide { color: ColorF { r: 0, g: 0, b: 0, a: 1 }, style: None }, right: BorderSide { color: ColorF { r: 0, g: 0, b: 0, a: 1 }, style: None }, top: BorderSide { color: ColorF { r: 0, g: 0, b: 0, a: 0.20000002 }, style: Solid }, bottom: BorderSide { color: ColorF { r: 0, g: 0, b: 0, a: 1 }, style: None }, radius: BorderRadius { top_left: 0×0, top_right: 0×0, bottom_left: 0×0, bottom_right: 0×0 } }) }), clip: ClipAndScrollInfo { scroll_node_id: Clip(3, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(11, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  BoxShadow(BoxShadowDisplayItem { box_bounds: TypedRect(613×35 at (221,35)), offset: (0,0), color: ColorF { r: 0.23137257, g: 0.6, b: 0.98823535, a: 0.4784314 }, blur_radius: 0, spread_radius: 1, border_radius: 4, clip_mode: Outset }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  BoxShadow(BoxShadowDisplayItem { box_bounds: TypedRect(613×35 at (221,35)), offset: (0,0), color: ColorF { r: 0.23137257, g: 0.6, b: 0.98823535, a: 0.4784314 }, blur_radius: 0, spread_radius: 1, border_radius: 4, clip_mode: Outset }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(12, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Rectangle(RectangleDisplayItem { color: ColorF { r: 1, g: 1, b: 1, a: 1 } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(12, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 110), stretch_size: 612×35, tile_spacing: 612×35, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Border(BorderDisplayItem { widths: BorderWidths { left: 1, top: 1, right: 1, bottom: 1 }, details: Normal(NormalBorder { left: BorderSide { color: ColorF { r: 0.23137257, g: 0.6, b: 0.98823535, a: 0.4784314 }, style: Solid }, right: BorderSide { color: ColorF { r: 0.23137257, g: 0.6, b: 0.98823535, a: 0.4784314 }, style: Solid }, top: BorderSide { color: ColorF { r: 0.23137257, g: 0.6, b: 0.98823535, a: 0.4784314 }, style: Solid }, bottom: BorderSide { color: ColorF { r: 0.23137257, g: 0.6, b: 0.98823535, a: 0.4784314 }, style: Solid }, radius: BorderRadius { top_left: 4×4, top_right: 4×4, bottom_left: 4×4, bottom_right: 4×4 } }) }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  BoxShadow(BoxShadowDisplayItem { box_bounds: TypedRect(189×30 at (844,37)), offset: (0,1), color: ColorF { r: 0, g: 0, b: 0, a: 0.050980397 }, blur_radius: 4, spread_radius: 0, border_radius: 4, clip_mode: Outset }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(13, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Rectangle(RectangleDisplayItem { color: ColorF { r: 1, g: 1, b: 1, a: 1 } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(13, 0, PipelineId(1, 1)), clip_node_id: None }
  Border(BorderDisplayItem { widths: BorderWidths { left: 1, top: 1, right: 1, bottom: 1 }, details: Normal(NormalBorder { left: BorderSide { color: ColorF { r: 0.04705883, g: 0.04705883, b: 0.050980397, a: 0.2509804 }, style: Solid }, right: BorderSide { color: ColorF { r: 0.04705883, g: 0.04705883, b: 0.050980397, a: 0.2509804 }, style: Solid }, top: BorderSide { color: ColorF { r: 0.04705883, g: 0.04705883, b: 0.050980397, a: 0.2509804 }, style: Solid }, bottom: BorderSide { color: ColorF { r: 0.04705883, g: 0.04705883, b: 0.050980397, a: 0.2509804 }, style: Solid }, radius: BorderRadius { top_left: 4×4, top_right: 4×4, bottom_left: 4×4, bottom_right: 4×4 } }) }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 28), stretch_size: 39×38, tile_spacing: 39×38, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(3, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 29), stretch_size: 28×28, tile_spacing: 28×28, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 30), stretch_size: 28×28, tile_spacing: 28×28, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(14, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 111), stretch_size: 16×16, tile_spacing: 16×16, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(14, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(15, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Rectangle(RectangleDisplayItem { color: ColorF { r: 0, g: 0, b: 0, a: 1 } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(15, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(16, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Text(TextDisplayItem { font_key: FontInstanceKey(IdNamespace(1), 10), color: ColorF { r: 0, g: 0, b: 0, a: 0.54 }, glyph_options: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(16, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 112), stretch_size: 16×16, tile_spacing: 16×16, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 48), stretch_size: 20×20, tile_spacing: 20×20, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(17, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Text(TextDisplayItem { font_key: FontInstanceKey(IdNamespace(1), 10), color: ColorF { r: 0, g: 0, b: 0, a: 0.54 }, glyph_options: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(17, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 33), stretch_size: 16×16, tile_spacing: 16×16, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 34), stretch_size: 28×28, tile_spacing: 28×28, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 49), stretch_size: 28×28, tile_spacing: 28×28, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 36), stretch_size: 16×16, tile_spacing: 16×16, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(3, 0, PipelineId(1, 1)), clip_node_id: None }
  PushStackingContext(PushStackingContextDisplayItem { stacking_context: StackingContext { scroll_policy: Scrollable, transform: None, transform_style: Flat, perspective: None, mix_blend_mode: Normal } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 43), stretch_size: 28×28, tile_spacing: 28×28, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  PopStackingContext, clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(18, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  PushStackingContext(PushStackingContextDisplayItem { stacking_context: StackingContext { scroll_policy: Scrollable, transform: Some(Value([-1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 805, 39, 0, 1])), transform_style: Flat, perspective: None, mix_blend_mode: Normal } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 113), stretch_size: 26×28, tile_spacing: 26×28, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  PopStackingContext, clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(19, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Rectangle(RectangleDisplayItem { color: ColorF { r: 1, g: 1, b: 1, a: 0.8000001 } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(19, 0, PipelineId(1, 1)), clip_node_id: None }
  Border(BorderDisplayItem { widths: BorderWidths { left: 1, top: 1, right: 1, bottom: 1 }, details: Normal(NormalBorder { left: BorderSide { color: ColorF { r: 0.04705883, g: 0.04705883, b: 0.050980397, a: 0.3019608 }, style: Solid }, right: BorderSide { color: ColorF { r: 0.04705883, g: 0.04705883, b: 0.050980397, a: 0.3019608 }, style: Solid }, top: BorderSide { color: ColorF { r: 0.04705883, g: 0.04705883, b: 0.050980397, a: 0.3019608 }, style: Solid }, bottom: BorderSide { color: ColorF { r: 0.04705883, g: 0.04705883, b: 0.050980397, a: 0.3019608 }, style: Solid }, radius: BorderRadius { top_left: 16×16, top_right: 16×16, bottom_left: 16×16, bottom_right: 16×16 } }) }), clip: ClipAndScrollInfo { scroll_node_id: Clip(11, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(20, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 46), stretch_size: 16×16, tile_spacing: 16×16, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(20, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(21, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Clip(ClipDisplayItem { id: Clip(22, 0, PipelineId(1, 1)), parent_id: Clip(0, 0, PipelineId(1, 1)), image_mask: None }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  PushStackingContext(PushStackingContextDisplayItem { stacking_context: StackingContext { scroll_policy: Scrollable, transform: None, transform_style: Flat, perspective: None, mix_blend_mode: Normal } }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  PopStackingContext, clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  PopNestedDisplayList, clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
  Image(ImageDisplayItem { image_key: ImageKey(IdNamespace(1), 24), stretch_size: 64×16, tile_spacing: 64×16, image_rendering: Auto }), clip: ClipAndScrollInfo { scroll_node_id: Clip(0, 0, PipelineId(1, 1)), clip_node_id: None }
```
</details>

**Comment by Pryx** [comment]
@Gankro is this crash related? Happens on Firefox Nightly on Linux 

`thread 'RenderBackend' panicked at 'Didn't find a cached resource with that ID!', /checkout/src/libcore/option.rs:823` 
Unfortunately AFAICT Nightly cannot provide a better backtrace.

**Comment by Gankro** [comment]
No that's probably https://bugzilla.mozilla.org/show_bug.cgi?id=1397407 which we're about to fix
