### ISSUE TITLE
Crash when using BinaryRecorder with non-IPC

### ISSUE THREAD

**Issue by nc4rrillo** [servo/webrender#1987]
Sending a hit_test API message triggers an unreachable code path in `channel_mpsc.rs`

```
thread 'RenderBackend' panicked at 'internal error: entered unreachable code', /home/nc4rrillo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/479d43a/webrender_api/src/channel_mpsc.rs:82:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: <webrender_api::channel::MsgSender<T> as serde::ser::Serialize>::serialize
             at ./<panic macros>:3
   7: <bincode::ser::SizeCompound<'a, S> as serde::ser::SerializeTupleVariant>::serialize_field
             at /home/nc4rrillo/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-0.9.2/src/ser/mod.rs:632
   8: webrender_api::api::_IMPL_SERIALIZE_FOR_DocumentMsg::<impl serde::ser::Serialize for webrender_api::api::DocumentMsg>::serialize
             at /home/nc4rrillo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/479d43a/webrender_api/src/api.rs:186
   9: <bincode::ser::SizeCompound<'a, S> as serde::ser::SerializeTupleVariant>::serialize_field
             at /home/nc4rrillo/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-0.9.2/src/ser/mod.rs:632
  10: webrender_api::api::_IMPL_SERIALIZE_FOR_ApiMsg::<impl serde::ser::Serialize for webrender_api::api::ApiMsg>::serialize
             at /home/nc4rrillo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/479d43a/webrender_api/src/api.rs:262
  11: bincode::internal::serialized_size
             at /home/nc4rrillo/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-0.9.2/src/internal.rs:222
  12: bincode::internal::serialize
             at /home/nc4rrillo/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-0.9.2/src/internal.rs:178
  13: bincode::serialize
             at /home/nc4rrillo/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-0.9.2/src/lib.rs:119
  14: <webrender::record::BinaryRecorder as webrender::record::ApiRecordingReceiver>::write_msg
             at /home/nc4rrillo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/479d43a/webrender/src/record.rs:52
  15: webrender::render_backend::RenderBackend::run
             at /home/nc4rrillo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/479d43a/webrender/src/render_backend.rs:459
  16: webrender::renderer::Renderer::new::{{closure}}
             at /home/nc4rrillo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/479d43a/webrender/src/renderer.rs:1811
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("receiving on a closed channel") }) }', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:772
  11: webrender_api::api::RenderApi::hit_test
             at /home/nc4rrillo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/479d43a/webrender_api/src/api.rs:680
  12: indigo_core::compositor::Compositor::handle_message
             at /home/nc4rrillo/Documents/projects/indigo/indigo_core/src/compositor/mod.rs:196
  13: indigo_core::compositor::Compositor::send_mouse_left
             at /home/nc4rrillo/Documents/projects/indigo/indigo_core/src/compositor/mod.rs:113
  14: indigo_core::ui::application::Application::new::{{closure}}
             at /home/nc4rrillo/Documents/projects/indigo/indigo_core/src/ui/application.rs:115
  15: winit::platform::platform::x11::EventsLoop::run_forever::{{closure}}
             at /home/nc4rrillo/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.8.3/src/platform/linux/x11/mod.rs:175
  16: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &'a mut F>::call_mut
             at /checkout/src/libcore/ops/function.rs:261
  17: winit::platform::platform::x11::EventsLoop::process_event
             at /home/nc4rrillo/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.8.3/src/platform/linux/x11/mod.rs:365
  18: winit::platform::platform::x11::EventsLoop::run_forever
             at /home/nc4rrillo/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.8.3/src/platform/linux/x11/mod.rs:180
  19: winit::platform::platform::EventsLoop::run_forever
             at /home/nc4rrillo/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.8.3/src/platform/linux/mod.rs:382
  20: winit::EventsLoop::run_forever
             at /home/nc4rrillo/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.8.3/src/lib.rs:229
  21: indigo_core::ui::application::Application::new
             at /home/nc4rrillo/Documents/projects/indigo/indigo_core/src/ui/application.rs:100
  22: indigo_sample::main
             at src/main.rs:179
  23: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  24: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  25: main
  26: __libc_start_main
  27: _start
```

**Comment by jrmuizel** [comment]
We use the binary recorder with non-ipc in Firefox (though not hit_test). Do you have steps that would make it easy to reproduce this?

**Comment by nc4rrillo** [comment]
I created a sample which reproduces here: https://github.com/nc4rrillo/wr-crash-sample
It does the bare minimum, creates a simple display list, then sends a hit test to WR.

STR:
- Click anywhere ;)

**Comment by kvark** [comment]
Happens on serializing an `MsgSender`:
```
/// These serialize methods are needed to satisfy the compiler
/// which uses these implementations for IPC, and also for the
/// recording tool. The recording tool only outputs messages
/// that don't contain Senders or Receivers, so in theory
/// these should never be called in the in-process config.
/// If they are called, there may be a bug in the messages
/// that the replay tool is writing.
```

**Comment by glennw** [comment]
I believe this will be resolved when https://github.com/servo/webrender/pull/1991 lands. If not, there may be another message that needs to be blacklisted.

**Comment by nc4rrillo** [comment]
Can confirm #1991 fixes this.
