### ISSUE TITLE
Profiler panic when replaying days-old recording

### ISSUE THREAD

**Issue by salty-horse** [servo/webrender#2201]
When I try to replay a recording from two days ago, the profiler does some arithmetic on a timestamp from the recording, and crashes:

The line is: `let send_time = consume_start - send_start;`
`consume_start` is 6,034,673,744,641, `send_start` is 44,473,796,935,259. The result is negative.

```
panicked at 'attempt to subtract with overflow'
  10: webrender::profiler::IpcProfileCounters::set
             at webrender/webrender/src/profiler.rs:394
  11: webrender::render_backend::RenderBackend::process_document
             at webrender/webrender/src/render_backend.rs:304
  12: webrender::render_backend::RenderBackend::run
             at webrender/webrender/src/render_backend.rs:491
  13: webrender::renderer::Renderer::new::{{closure}}
             at webrender/webrender/src/renderer.rs:2034
```

Should the profiler be used at all during replays?

**Comment by glennw** [comment]
Ah, interesting. I guess this is since one of the timestamps is stored in the replay and one is calculated at runtime. Which does indeed mean that the IPC timings are completely wrong during a replay. I'm not sure what the easiest way is to disable it during replay, but that does sound like the correct solution.
