### ISSUE TITLE
Panic when starting up gecko+webrender on Windows

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2208]
This is the panic from https://bugzilla.mozilla.org/show_bug.cgi?id=1424280#c8, which is a regression from #2162. I was able to reproduce it on a local windows debug build and got a better stack:

```
thread '<unnamed>' panicked at 'index 5121 out of range for slice of length 5120', src\libcore\slice\mod.rs:746:4
stack backtrace:
   0:     0x7ffd6c9992e1 - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:92
   1:     0x7ffd6c9b0d4c - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:380
   2:     0x7ffd6c9b08f5 - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:397
   3:     0x7ffd6c9b1545 - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:577
   4:     0x7ffd6c9b13b8 - std::panicking::begin_panic<alloc::string::String>
                               at C:\projects\rust\src\libstd\panicking.rs:538
   5:     0x7ffd6c9b1241 - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:522
   6:     0x7ffd6c9b119f - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:498
   7:     0x7ffd6d0ace5e - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:71
   8:     0x7ffd6d0acf71 - core::slice::slice_index_len_fail
                               at C:\projects\rust\src\libcore\slice\mod.rs:746
   9:     0x7ffd6d4b514e - core::slice::{{impl}}::index_mut<webrender::gpu_cache::GpuBlockData>
                               at C:\projects\rust\src\libcore\slice\mod.rs:889
  10:     0x7ffd6d493f73 - core::slice::{{impl}}::index_mut<webrender::gpu_cache::GpuBlockData,core::ops::range::Range<usize>>
                               at C:\projects\rust\src\libcore\slice\mod.rs:739
  11:     0x7ffd6d45aff5 - alloc::vec::{{impl}}::index_mut<webrender::gpu_cache::GpuBlockData>
                               at C:\projects\rust\src\liballoc\vec.rs:1625
  12:     0x7ffd6d4c977d - webrender::renderer::CacheTexture::update
                               at C:\Users\kats\zspace\mozilla-wr\gfx\webrender\src\renderer.rs:970
  13:     0x7ffd6d4d3f83 - webrender::renderer::Renderer::prepare_gpu_cache
                               at C:\Users\kats\zspace\mozilla-wr\gfx\webrender\src\renderer.rs:2846
  14:     0x7ffd6d4d3b2f - webrender::renderer::{{impl}}::render::{{closure}}
                               at C:\Users\kats\zspace\mozilla-wr\gfx\webrender\src\renderer.rs:2736
  15:     0x7ffd6d4c0e4a - webrender::profiler::TimeProfileCounter::profile<(),closure>
                               at C:\Users\kats\zspace\mozilla-wr\gfx\webrender\src\profiler.rs:190
  16:     0x7ffd6d4d3341 - webrender::renderer::Renderer::render
                               at C:\Users\kats\zspace\mozilla-wr\gfx\webrender\src\renderer.rs:2696
  17:     0x7ffd6c93e8d9 - webrender_bindings::bindings::wr_renderer_render
                               at C:\Users\kats\zspace\mozilla-wr\gfx\webrender_bindings\src\bindings.rs:509
  18:     0x7ffd6f004929 - mozilla::wr::RendererOGL::Render
                               at c:\users\kats\zspace\mozilla-wr\gfx\webrender_bindings\rendererogl.cpp:149
  19:     0x7ffd6f006a91 - mozilla::wr::RenderThread::UpdateAndRender
                               at c:\users\kats\zspace\mozilla-wr\gfx\webrender_bindings\renderthread.cpp:228
  20:     0x7ffd6f002794 - mozilla::wr::RenderThread::NewFrameReady
                               at c:\users\kats\zspace\mozilla-wr\gfx\webrender_bindings\renderthread.cpp:174
  21:     0x7ffd6f004e62 - mozilla::detail::RunnableMethodImpl<mozilla::wr::RenderThread * __ptr64,void (__cdecl mozilla::wr::RenderThread::*)(mozilla::wr::WrWindowId) __ptr64,1,0,mozilla::wr::WrWindowId>::Run
                               at c:\users\kats\zspace\mozilla-wr\obj-win64-debug\dist\include\nsthreadutils.h:1192
  22:     0x7ffd6e186840 - MessageLoop::RunTask
                               at c:\users\kats\zspace\mozilla-wr\ipc\chromium\src\base\message_loop.cc:452
  23:     0x7ffd6e17e936 - MessageLoop::DeferOrRunPendingTask
                               at c:\users\kats\zspace\mozilla-wr\ipc\chromium\src\base\message_loop.cc:460
  24:     0x7ffd6e17f2ad - MessageLoop::DoWork
                               at c:\users\kats\zspace\mozilla-wr\ipc\chromium\src\base\message_loop.cc:535
  25:     0x7ffd6e18650f - base::MessagePumpDefault::Run
                               at c:\users\kats\zspace\mozilla-wr\ipc\chromium\src\base\message_pump_default.cc:36
  26:     0x7ffd6e1866fd - MessageLoop::RunHandler
                               at c:\users\kats\zspace\mozilla-wr\ipc\chromium\src\base\message_loop.cc:319
  27:     0x7ffd6e18621d - MessageLoop::Run
                               at c:\users\kats\zspace\mozilla-wr\ipc\chromium\src\base\message_loop.cc:299
  28:     0x7ffd6e187da8 - base::Thread::ThreadMain
                               at c:\users\kats\zspace\mozilla-wr\ipc\chromium\src\base\thread.cc:181
  29:     0x7ffd6e16cb1d - `anonymous namespace'::ThreadFunc
                               at c:\users\kats\zspace\mozilla-wr\ipc\chromium\src\base\platform_thread_win.cc:28
  30:     0x7ffdb2d41fe3 - BaseThreadInitThunk
```

This points to the line at https://github.com/servo/webrender/blob/2c5c04369ac8d07ee3ba708c0f45e67e09b55581/webrender/src/renderer.rs#L970 as being the culprit.

**Comment by staktrace** [comment]
Added some logging to see what the values were:

block_offset: 8191 block_count 2 row 7 MAX_VERTEX_TEXTURE_WIDTH 1024 address.v 7 address.u 1023
thread '<unnamed>' panicked at 'index 8193 out of range for slice of length 8192', src\libcore\slice\mod.rs:746:4

So in this case block_offset (8191) is within the slice length (8192), but if you add the block_count (2) it goes over. I don't really know what this code is doing so I'm not sure what the expected behaviour is.

**Comment by glennw** [comment]
cc @kvark

**Comment by glennw** [comment]
I think this same panic is occurring in the WR update PR for Servo - see:

http://build.servo.org/builders/linux-rel-wpt/builds/7240/steps/shell__2/logs/filtered-wpt-errorsummary.log http://build.servo.org/builders/linux-rel-wpt/builds/7240/steps/test__1/logs/stdio
https://github.com/servo/servo/pull/19531#issuecomment-350429510
