### ISSUE TITLE
Mac CI is broken

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2638]
I seem to have to broken it to cause osmesa not to build:

```
make[4]: /Users/tcworker/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/1cf8c2f/mesa-src/bin/install-sh: Permission denied
make[4]: /Users/tcworker/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/1cf8c2f/mesa-src/bin/install-sh: Permission denied
make[4]: *** [os/.deps/.dirstamp] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [pipebuffer/.deps/.dirstamp] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
thread 'main' panicked at 'failed with: exit code: 2', /Users/tcworker/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/1cf8c2f/build.rs:58:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:68
             at src/libstd/sys_common/backtrace.rs:57
             at src/libstd/panicking.rs:381
   2: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   3: std::panicking::begin_panic
             at src/libstd/panicking.rs:577
   4: std::panicking::begin_panic
             at src/libstd/panicking.rs:538
   5: std::panicking::try::do_call
             at src/libstd/panicking.rs:522
   6: build_script_build::run
             at ./build.rs:58
   7: build_script_build::main
             at ./build.rs:45
   8: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
   9: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:480
  10: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:101
  11: std::sys_common::bytestring::debug_fmt_bytestring
             at src/libstd/panicking.rs:459
             at src/libstd/panic.rs:365
             at src/libstd/rt.rs:58
```

**Comment by jrmuizel** [comment]
So the 
`make[4]: /Users/tcworker/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/1cf8c2f/mesa-src/bin/install-sh: Permission denied` error makes no sense to me.

`/Users/tcworker/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/1cf8c2f/mesa-src/bin/install-sh` exists and is executable by `tcworker`. In fact it is usually used in earlier stages of the build successfully.

I tried to see if it was being modified during the build using https://github.com/jrmuizel/fslogger but nothing showed up.

The cause of this as far as I can tell is logging in graphically using the tcworker.

**Comment by jrmuizel** [comment]
I've since tried logging out. That does not help.

**Comment by glennw** [comment]
This seems to be working now. Please re-open if there is more work to do here.
