### ISSUE TITLE
gpu_cache hits debug_assert over mismatched epochs

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#2667]
Scrolling around https://gankro.github.io/blah/webtests/text.html in gecko causes this very quickly (may need to shrink window vertically)

It seems to be related to text-shadows, as in release builds they will fail to render when first scrolled onto screen (and this is very visible thanks to APZ).

The assertion is in `GpuCache::get_address`, but my stack seems to be messed up:

```
thread 'WRRenderBackend#1' panicked at 'assertion failed: `(left == right)`
  left: `Epoch(11)`,
 right: `Epoch(10)`', gfx/webrender/src/gpu_cache.rs:646:9
stack backtrace:
   0:     0x7f47aa8bdb5b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hb18bafd8df1a59a5
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f47aa8d1a6e - std::sys_common::backtrace::print::he2db06f5f327c580
                               at /checkout/src/libstd/sys_common/backtrace.rs:68
                               at /checkout/src/libstd/sys_common/backtrace.rs:57
   2:     0x7f47aa8ac290 - std::panicking::default_hook::{{closure}}::hef814c3eb720780d
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x7f47aa8abdcc - std::panicking::default_hook::hf0d3601b84335f7c
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x7f47aa8ac79b - std::panicking::rust_panic_with_hook::hf9f34d7f0d667943
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x7f47aa8ac5ee - std::panicking::begin_panic::h215af23ff6354aaf
                               at /checkout/src/libstd/panicking.rs:538
   6:     0x7f47aa8ac55a - std::panicking::begin_panic_fmt::h752224a2c436be23
                               at /checkout/src/libstd/panicking.rs:522
   7:     0x7f47aa788467 - <unknown>
                               at gfx/webrender/src/gpu_cache.rs:0
Redirecting call to abort() to mozalloc_abort

Hit MOZ_CRASH() at /home/alexis/gecko/gecko/memory/mozalloc/mozalloc_abort.cpp:34

Program /home/alexis/gecko/gecko/obj-debug/dist/bin/firefox (pid = 11913) received signal 11.
Stack:
#01: ???[/home/alexis/gecko/gecko/obj-debug/dist/bin/libxul.so +0x88494d4]
#02: ???[/home/alexis/gecko/gecko/obj-debug/dist/bin/libxul.so +0x87d7433]
#03: ???[/lib/x86_64-linux-gnu/libpthread.so.0 +0x11390]
#04: mozalloc_abort(char const*)[/home/alexis/gecko/gecko/obj-debug/dist/bin/firefox +0x2048c]
#05: ???[/home/alexis/gecko/gecko/obj-debug/dist/bin/firefox +0x204b6]
#06: __rust_start_panic[/home/alexis/gecko/gecko/obj-debug/dist/bin/libxul.so +0x91e85f9]
```

Bugzilled: https://bugzilla.mozilla.org/show_bug.cgi?id=1454538

**Comment by glennw** [comment]
I'll look at this today.

**Comment by glennw** [comment]
@kvark is already looking into this :)

**Comment by Gankro** [comment]
it's possible this was caused by https://github.com/servo/webrender/pull/2588

see https://bugzilla.mozilla.org/show_bug.cgi?id=1454538#c6

**Comment by glennw** [comment]
Yup, that seems quite likely to be the cause of it.
