### ISSUE TITLE
webrender crashes with feature=pathfinder on Windows

### ISSUE THREAD

**Issue by fschutt** [servo/webrender#2791]
Since the last changes in webrender (https://github.com/servo/webrender/commit/5e4f257d9f3cdb5691ac62f3affe2e9189d66447) added some changes to pathfinder, I wanted to see if pathfinder works now on Windows. I had previously noted that there was a bug (see the PR notes for #2723), but this seems to be a **new** bug, unrelated to the previous one. 

So what I did, was that I tried to run the debug example for azul:

```toml
[dependencies.webrender]
git = "https://github.com/servo/webrender"
rev = "5e4f257d9f3cdb5691ac62f3affe2e9189d66447"
default-features = false
features = ["pathfinder"]
```

When done without `default-features=false + features = ["pathfinder"]`, I get this:

![image](https://user-images.githubusercontent.com/12084016/40710729-b7daea0e-63f9-11e8-9e07-744f7770a677.png)

With pathfinder, it crashes with:

```
thread 'main' panicked at 'assertion failed: thread::panicking() || self.id == 0', C:\Users\fschutt\.cargo\git\checkouts\webrender-c3596abe1cf4f320\5e4f257\webrender\src\device.rs:503:9
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:207
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:223
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:402
   6: std::panicking::begin_panic<str*>
             at C:\projects\rust\src\libstd\panicking.rs:365
   7: webrender::device::{{impl}}::drop
             at <unknown>:503
   8: core::ptr::drop_in_place<webrender::device::Texture>
             at C:\projects\rust\src\libcore\ptr.rs:59
   9: core::ptr::drop_in_place<webrender::gpu_glyph_renderer::StenciledGlyphPage>
             at C:\projects\rust\src\libcore\ptr.rs:59
  10: webrender::renderer::Renderer::stencil_glyphs
             at <unknown>:227
  11: webrender::renderer::Renderer::draw_texture_cache_target
             at <unknown>:3313
  12: webrender::renderer::Renderer::draw_tile_frame
             at <unknown>:3653
  13: webrender::renderer::{{impl}}::render_impl::{{closure}}
             at <unknown>:2345
  14: webrender::profiler::TimeProfileCounter::profile<(),closure>
             at <unknown>:204
  15: webrender::renderer::Renderer::render_impl
             at <unknown>:2298
  16: webrender::renderer::Renderer::render
             at <unknown>:2243
  17: azul::app::render<debug::MyAppData>
             at <unknown>:499
  18: azul::app::App<debug::MyAppData>::run<debug::MyAppData>
             at <unknown>:186
  19: debug::main
             at <unknown>:68
  20: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  21: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  22: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:306
  23: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:102
  24: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:285
  25: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:361
  26: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  27: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  28: main
  29: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  30: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  31: BaseThreadInitThunk
  32: RtlUserThreadStart



thread 'main' panicked at 'assertion failed: !self.inside_frame', C:\Users\fschutt\.cargo\git\checkouts\webrender-c3596abe1cf4f320\5e4f257\webrender\src\device.rs:873:9
stack backtrace:
   0:     0x7ff64431670a - std::sys::windows::backtrace::unwind_backtrace
                               at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1:     0x7ff64431b90f - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2:     0x7ff64431b90f - std::sys_common::backtrace::print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff644309e0e - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:207
   4:     0x7ff644309aba - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:223
   5:     0x7ff64430a3ce - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:402
   6:     0x7ff643b0e2c6 - std::panicking::begin_panic<str*>
                               at C:\projects\rust\src\libstd\panicking.rs:365
   7:     0x7ff6439d4a51 - webrender::device::Device::begin_frame
                               at <unknown>:873
   8:     0x7ff643986bb1 - webrender::renderer::Renderer::deinit
                               at <unknown>:3945
   9:     0x7ff6435a5446 - azul::window::{{impl}}::drop<debug::MyAppData>
                               at <unknown>:676
  10:     0x7ff643607a6e - core::ptr::drop_in_place<azul::window::Window<debug::MyAppData>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  11:     0x7ff64360f1f6 - core::ptr::drop_in_place<slice<azul::window::Window<debug::MyAppData>>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  12:     0x7ff6435d0f5b - alloc::vec::{{impl}}::drop<azul::window::Window<debug::MyAppData>>
                               at C:\projects\rust\src\liballoc\vec.rs:2106
  13:     0x7ff64361583e - core::ptr::drop_in_place<alloc::vec::Vec<azul::window::Window<debug::MyAppData>>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  14:     0x7ff64361923e - core::ptr::drop_in_place<azul::app::App<debug::MyAppData>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  15:     0x7ff6435ef679 - debug::main
                               at <unknown>:69
  16:     0x7ffbaee2c83f - _C_specific_handler
  17:     0x7ffbaee22be6 - _TypeMatch
  18:     0x7ffbaee21ee2 - is_exception_typeof
  19:     0x7ffbaee2bf2f - _CxxFrameHandler3
  20:     0x7ffbb66d351c - _chkstk
  21:     0x7ffbb6695494 - RtlUnwindEx
  22:     0x7ffbaee2c2d8 - FindAndUnlinkFrame
  23:     0x7ffbaee22d38 - _TypeMatch
  24:     0x7ffbaee223dd - is_exception_typeof
  25:     0x7ffbaee21fde - is_exception_typeof
  26:     0x7ffbaee2bf2f - _CxxFrameHandler3
  27:     0x7ffbb66d349c - _chkstk
  28:     0x7ffbb66948d6 - RtlRaiseException
  29:     0x7ffbb6693afc - RtlRaiseException
  30:     0x7ffbb3b38eab - RaiseException
  31:     0x7ffbaee24721 - CxxThrowException
  32:     0x7ff64431eceb - panic_unwind::imp::panic
                               at C:\projects\rust\src\libpanic_unwind\seh.rs:291
  33:     0x7ff64431eceb - panic_unwind::__rust_start_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:118
  34:     0x7ff64430a58e - std::panicking::rust_panic
                               at C:\projects\rust\src\libstd\panicking.rs:433
  35:     0x7ff64430a49b - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:418
  36:     0x7ff643b0e2c6 - std::panicking::begin_panic<str*>
                               at C:\projects\rust\src\libstd\panicking.rs:365
  37:     0x7ff6439d2a5d - webrender::device::{{impl}}::drop
                               at <unknown>:503
  38:     0x7ff643a3354e - core::ptr::drop_in_place<webrender::device::Texture>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  39:     0x7ff643a2c05e - core::ptr::drop_in_place<webrender::gpu_glyph_renderer::StenciledGlyphPage>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  40:     0x7ff643969365 - webrender::renderer::Renderer::stencil_glyphs
                               at <unknown>:227
  41:     0x7ff643982108 - webrender::renderer::Renderer::draw_texture_cache_target
                               at <unknown>:3313
  42:     0x7ff6439853bf - webrender::renderer::Renderer::draw_tile_frame
                               at <unknown>:3653
  43:     0x7ff643978e82 - webrender::renderer::{{impl}}::render_impl::{{closure}}
                               at <unknown>:2345
  44:     0x7ff643c02ae2 - webrender::profiler::TimeProfileCounter::profile<(),closure>
                               at <unknown>:204
  45:     0x7ff6439782c4 - webrender::renderer::Renderer::render_impl
                               at <unknown>:2298
  46:     0x7ff643978187 - webrender::renderer::Renderer::render
                               at <unknown>:2243
  47:     0x7ff6436450c3 - azul::app::render<debug::MyAppData>
                               at <unknown>:499
  48:     0x7ff643643e50 - azul::app::App<debug::MyAppData>::run<debug::MyAppData>
                               at <unknown>:186
  49:     0x7ff6435ef601 - debug::main
                               at <unknown>:68
  50:     0x7ff6436b4763 - std::rt::lang_start::{{closure}}<()>
                               at C:\projects\rust\src\libstd\rt.rs:74
  51:     0x7ff644309fdc - std::rt::lang_start_internal::{{closure}}
                               at C:\projects\rust\src\libstd\rt.rs:59
  52:     0x7ff644309fdc - std::panicking::try::do_call<closure,i32>
                               at C:\projects\rust\src\libstd\panicking.rs:306
  53:     0x7ff64431ec11 - panic_unwind::__rust_maybe_catch_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:102
  54:     0x7ff644316372 - std::panicking::try
                               at C:\projects\rust\src\libstd\panicking.rs:285
  55:     0x7ff644316372 - std::panic::catch_unwind
                               at C:\projects\rust\src\libstd\panic.rs:361
  56:     0x7ff644316372 - std::rt::lang_start_internal
                               at C:\projects\rust\src\libstd\rt.rs:58
  57:     0x7ff6436b4733 - std::rt::lang_start<()>
                               at C:\projects\rust\src\libstd\rt.rs:74
  58:     0x7ff6435ef6b6 - main
  59:     0x7ff64432eeeb - invoke_main
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  60:     0x7ff64432eeeb - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  61:     0x7ffbb42113d1 - BaseThreadInitThunk
  62:     0x7ffbb66554f3 - RtlUserThreadStart
```

For a short moment, a black screen is shown (before the program crashes). I am currently not familiar with how to set up .yaml scenes - is there any way to get them out of a `DisplayListBuilder` or a `BuiltDisplayList`? Then I could maybe produce a reproducable test case.

**Comment by kvark** [comment]
The assertion is pretty clear here, should be easy to fix (e.g. by inserting `begin_frame` + `end_frame` boundaries where appropriate).

**Comment by nc4rrillo** [comment]
I'm getting an early return in `stencil_glyphs` due to `packer.add(&stencil_size)` returning an Err.
The glyph dimensions are huge (1356×1516) which..doesn't sound right to me..

I suspect its something to do with how glyph metrics are calculated in the dwrite implementation in Pathfinder

**Comment by fschutt** [comment]
@nc4rrillo The glyph dimensions look fine to me, they are not in pixels, but in dpi-independent unscaled font units. Take the glyph dimensions / 72, then you should get the real pixel size.

**Comment by nc4rrillo** [comment]
Oh! Makes sense :). I'm still getting an early return there though which causes `Texture` to drop and that assertion to be hit.

**Comment by fschutt** [comment]
@kvark Did you mean the `begin_frame + end_frame` has to be done on my side? To me, it looks like a bug in webrender, all I'm really doing is just calling `DisplayListBuilder::push_text()`. Which works fine without pathfinder.

**Comment by kvark** [comment]
@fschutt oh no, it's definitely not on your side.

**Comment by gw3583** [comment]
cc @pcwalton

**Comment by fschutt** [comment]
Housekeeping on my own old issues - closing this one out. azul, which is what I filed it for, has been building against a vendored WebRender fork for a while now, so I am no longer tracking this upstream. Please reopen if it is still worth having on file.
