### ISSUE TITLE
Calling webrender::Renderer deinit results in panic.

### ISSUE THREAD

**Issue by pekim** [servo/webrender#2793]
With the `pathfinder`, feature calling a `webrender::Renderer` instance's `deinit` results in panic.
This does not happen when using freetype.

```
thread '<unnamed>' panicked at 'assertion failed: thread::panicking() || self.id == 0', /home/mike/.cargo/git/checkouts/webrender-c3596abe1cf4f320/52ba116/webrender/src/device.rs:503:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:397
   6: <webrender::device::Texture as core::ops::drop::Drop>::drop
             at /home/mike/.cargo/git/checkouts/webrender-c3596abe1cf4f320/52ba116/webrender/src/device.rs:503
   7: core::ptr::drop_in_place
             at /checkout/src/libcore/ptr.rs:59
   8: core::ptr::drop_in_place
             at /checkout/src/libcore/ptr.rs:59
   9: webrender::renderer::Renderer::deinit
             at /home/mike/.cargo/git/checkouts/webrender-c3596abe1cf4f320/52ba116/webrender/src/renderer.rs:3957
  10: tonbridge_webrender::render::web_render_context::WebRenderContext::deinit
             at src/render/web_render_context.rs:72
  11: <tonbridge_webrender::window::Window as core::ops::drop::Drop>::drop
             at src/window.rs:23
  12: core::ptr::drop_in_place
             at /checkout/src/libcore/ptr.rs:59
  13: core::ptr::drop_in_place
             at /checkout/src/libcore/ptr.rs:59
  14: tb_destroy_window
             at src/window.rs:193
  15: <unknown>
             at /usr/local/go/src/runtime/asm_amd64.s:688
```

**Comment by kvark** [comment]
The assertion appears to match #2791

**Comment by pekim** [comment]
In that issue it's occurring during `Renderer::render`, and I was experiencing it from `Renderer::deinit`. As the scenario is slightly different I wasn't sure whether it's got the same root cause or not.

**Comment by gw3583** [comment]
cc @pcwalton

**Comment by pekim** [comment]
I've just updated from 52ba116 to c939a61, and this is no longer happening.
