### ISSUE TITLE
wrench crashes on Fedora 40 under Wayland

### ISSUE THREAD

**Issue by hovinen** [servo/webrender#4851]
When I run:

```
git clone https://github.com/servo/webrender.git
cd webrender/wrench
RUST_BACKTRACE=1 cargo run --release -- load ~/wr-capture
```

I get the following:

```
     Running `<redacted>/webrender/target/release/wrench load <redacted>/wr-capture`
interface 'wl_surface' has no event 2
thread 'main' panicked at wrench/src/main.rs:362:18:
called `Result::unwrap()` on an `Err` value: OsError("eglInitialize failed")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   3: wrench::make_window
   4: wrench::main
             at ./src/main.rs:681:22
   5: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```

I get similar output with all other `wrench` commands I have tried, e.g. `cargo run -- test_init`.

This looks like the same problem as https://github.com/wez/wezterm/issues/3996, which apparently required updating a dependency.

All of this is on Fedora 40 running mutter 46.1 as its Wayland compositor.

**Comment by mrobinson** [comment]
It would be best to report this issue upstream in Gecko. This repository tracks our downstream fork of WebRender for use in Servo.

**Comment by hovinen** [comment]
Thanks. I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1895685.
